# Generated by Django 5.2.7 on 2025-11-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='codigo_acceso',
            field=models.CharField(default='temp', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='autor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contacto'),
        ),
    ]
