# Generated by Django 5.2.7 on 2025-11-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ticket_codigo_acceso_alter_message_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='codigo_acceso',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
